# -*- coding: utf-8 -*-
"""Python - Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mS02TL88C0ZbwoidtHcOcKiDVjwiZXKC
"""

# Function to perform addition
def add(a, b):
    return a + b

# Function to perform subtraction
def subtract(a, b):
    return a - b

# Function to perform multiplication
def multiply(a, b):
    return a * b

# Function to perform division
def divide(a, b):
    try:
        return a / b
    except ZeroDivisionError:
        return "Error! Division by zero is not allowed."

# Display options to the user
def show_menu():
    print("\nSelect an operation:")
    print("1. Addition")
    print("2. Subtraction")
    print("3. Multiplication")
    print("4. Division")
    print("5. Exit")

# Main program loop
while True:
    # Show the menu
    show_menu()

    # Take user input for the operation
    choice = input("\nEnter your choice (1-5): ")

    # Check if the user wants to exit
    if choice == '5':
        print("Exiting the calculator. Goodbye!")
        break

    # Ensure the user enters a valid choice
    if choice not in ['1', '2', '3', '4']:
        print("Invalid choice. Please select a valid option from 1 to 5.")
        continue

    # Get two numbers from the user with error handling
    try:
        num1 = float(input("Enter the first number: "))
        num2 = float(input("Enter the second number: "))
    except ValueError:
        print("Invalid input! Please enter numeric values only.")
        continue

    # Perform the selected operation and display the result
    try:
        if choice == '1':
            print(f"The result is: {add(num1, num2)}")
        elif choice == '2':
            print(f"The result is: {subtract(num1, num2)}")
        elif choice == '3':
            print(f"The result is: {multiply(num1, num2)}")
        elif choice == '4':
            print(f"The result is: {divide(num1, num2)}")
    except Exception as e:
        # Catch any unexpected errors
        print(f"An unexpected error occurred: {e}")